// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_iou`, `generate_priors_640`, `hard_nms`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Face`, `Prior`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<Uint8List> blurFaceArea({
  required List<int> imageBytes,
  required int x,
  required int y,
  required int w,
  required int h,
}) => RustLib.instance.api.crateApiSimpleBlurFaceArea(
  imageBytes: imageBytes,
  x: x,
  y: y,
  w: w,
  h: h,
);

Future<List<BlurRect>> detectFacesDesktop({
  required List<int> imageBytes,
  required List<int> modelBytes,
}) => RustLib.instance.api.crateApiSimpleDetectFacesDesktop(
  imageBytes: imageBytes,
  modelBytes: modelBytes,
);

Future<Uint8List> blurMultipleFaces({
  required List<int> imageBytes,
  required List<BlurRect> rects,
  required bool isCircle,
}) => RustLib.instance.api.crateApiSimpleBlurMultipleFaces(
  imageBytes: imageBytes,
  rects: rects,
  isCircle: isCircle,
);

@freezed
sealed class BlurRect with _$BlurRect {
  const factory BlurRect({
    required int x,
    required int y,
    required int w,
    required int h,
  }) = _BlurRect;
}
